[package]
name = "cato-display-app"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.27.0"
iced = { version = "0.12.1", features = ["canvas", "lazy", "tokio"] }
iced_core = "0.12.3"
reqwest = "0.12.4"
